// Generated by gencpp from file tutorial/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TUTORIAL_MESSAGE_ADDTWOINTS_H
#define TUTORIAL_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <tutorial/AddTwoIntsRequest.h>
#include <tutorial/AddTwoIntsResponse.h>


namespace tutorial
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace tutorial


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::tutorial::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::tutorial::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::tutorial::AddTwoInts > {
  static const char* value()
  {
    return "tutorial/AddTwoInts";
  }

  static const char* value(const ::tutorial::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::tutorial::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::AddTwoIntsRequest> should match 
// service_traits::DataType< ::tutorial::AddTwoInts > 
template<>
struct DataType< ::tutorial::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::tutorial::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::tutorial::AddTwoInts > 
template<>
struct MD5Sum< ::tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::tutorial::AddTwoIntsResponse> should match 
// service_traits::DataType< ::tutorial::AddTwoInts > 
template<>
struct DataType< ::tutorial::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::tutorial::AddTwoInts >::value();
  }
  static const char* value(const ::tutorial::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TUTORIAL_MESSAGE_ADDTWOINTS_H
